title: llab-2
tagline: A brand new course on Learning Lab
description: test
template:
  repo: llab-2-template
  name: llab-2
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
